title: Alma Delia
logo: /assets/img/Delia.png
description: Contribuir en la creación de soluciones web innovadoras, que cumplan con las expectativas y contribuyan a la reputación de 
la empresa en el ámbito tecnológico mediante la aplicación de habilidades tecnicas y experiencia en el desarrollo web.
show_downloads: true
theme: jekyll-theme-minimal
